export enum SecondSideBarAuthority {
    ACCESS_ACTS = "menu:acts",
    ACCESS_ANTECEDENT = "menu:access_antecedent",
    ACCESS_INSURANCE = "menu:access_insurance",
    ACCESS_CASHIERS = "menu:access_cashiers",
    ACCESS_CONSTANTS = "menu:access_constant",
    ACCESS_CONVENTION = "menu:access_convention",
    ACCESS_DOCUMENT_TYPE = "menu:access_document_type",
    ACCESS_FACILITY = "menu:access_facility",
    ACCESS_PATHOLOGY = "menu:access_pathology",
    ACCESS_PHARMACY = "menu:access_pharmacy",
    ACCESS_PRACTICIAN = "menu:access_practician",
    ACCESS_WAITING_ROOM = "menu:access_waiting_room",
    ACCESS_STOCK = "menu:access_stock",
    ACCESS_SPECIALITY = "menu:access_speciality",
    ACCESS_TERRITORIAL_SUBDIVISION = "menu:access_territorial_subdivision",
    ACCESS_SYMPTOMS = "menu:access_symptoms",
    ACCESS_PAYMENT_TYPE = "menu:access_payment_type",
    ACCESS_BASIC_FILES = "menu:basic_files",
    ACCESS_USER_MANAGEMENT = "menu:user_managenement",
    ACCESS_EVENT_LOG = "event_log:list",
    ACCESS_APPLICATION_SETTINGS = "app_param:setting",
}